all:
# Solidity compiler
	npm install --save solc
	
# ganache-cli, Mocha, Web3 (v1.0.0-beta.26)
	npm install --save mocha ganache-cli web3@1.0.0-beta.26
# Web3 v0.x.x (primitive interface - only callbacks for async code), v1.x.x (support promises + async/await)

# Truffle HDWallet Provider
	npm install --save truffle-hdwallet-provider