all:
# install Truffle
	npm install -g truffle@5.0.5

# Downlad and Install Ganache GUI

# Use OpenZepplin (54ee1c7) commited on 4 Sep 2019 [LINK: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/54ee1c7ff59462bc300c0dc96cb71eb1e3cbdb45]


